- hosts: all
  tasks:
    - name: "Update packages"
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: "Install apt-transport-https"
      apt:
        name: ['apt-transport-https']
        state: latest
    - name: "Install ca-certificatess"
      apt:
        name: ['ca-certificates']
        state: latest
    - name: "Install curl"
      apt:
        name: ['curl']
        state: latest
    - name: "Install software-properties-common"
      apt:
        name: ['software-properties-common']
        state: latest
    - name: Get GPG
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    - name: Add Repository
      shell:  add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable\"
    - name: "Update packages"
      apt:
        update_cache: yes
