- hosts: all
  tasks:
    - name: Execute a command
      shell: vi Dockerfile
    - name: Crea Dockerfile
      shell:
          cmd: |
              cat <<EOT > Dockerfile
              FROM nginx:latest
              MAINTEINER Josue Rio Campos Becerra
              COPY public/ /usr/share/nginx/html/
              EOT
    - name:  Build Image
      shell: docker build -t \"${env.DOCKER_REPO}/${JOB_BASE_NAME}:${BUILD_NUMBER} .\" 
    - name:  Publish Image
      shell: 
          cmd: |
              docker login -u \"$docker_user -p $docker_pass\"
              docker push \"${env.DOCKER_REPO}/${JOB_BASE_NAME}:${BUILD_NUMBER}\"
       
